### ISSUE TITLE
[1.7.10] Refilling Charm not triggering any animation

### ISSUE THREAD

**Issue by CoderInOrbit** [HarryPotterSpells/HarryPotterSpells#45]
Hi,

Refilling Charm works fine on buckets, but no animation gets emitted whatsoever.

Here are the logs : 

>02.07 22:27:10 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
>02.07 22:27:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
>02.07 22:27:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
>02.07 22:27:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
>02.07 22:27:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
>02.07 22:27:10 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>02.07 22:27:10 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>02.07 22:27:10 [Server] INFO at com.hpspells.core.Listeners$1.run(Listeners.java:155) ~[?:?]
>02.07 22:27:10 [Server] INFO at com.hpspells.core.spell.SpellManager.cleverCast(SpellManager.java:222) ~[?:?]
>02.07 22:27:10 [Server] INFO at com.hpspells.core.spell.RefillingCharm.cast(RefillingCharm.java:32) ~[?:?]
>02.07 22:27:10 [Server] INFO java.lang.NullPointerException
>02.07 22:27:10 [Server] WARN Task #17277 for HarryPotterSpells v1.1.4 BETA generated an exception

Using latest version of HPS on Jenkins

Thanks!

**Comment by jacklin213** [comment]
Its come to my understanding that Refilling Charm doesn't actually have a particle effect. This will be a milestone for 1.1.6
