### ISSUE TITLE
Bug with Expelliarmus spell

### ISSUE THREAD

**Issue by TheRealVIG0R** [HarryPotterSpells/HarryPotterSpells#83]
**Please complete the following information):**
 - OS: Windows
 - Server type: Spigot
 - Server Version: 1.12.2 R0.1-Snapshot
 - HPS Version: 1.1.9 BETA
 - List of plugins: AcademyClasses, Admin-Chat-1.4.4, ArmorStandTools, BroomSticks, ChatManager_3.6.2, Citizens, CitizensText, CommandNPC-1.9.1, CraftBook+3.9u22, CratesPlus-4.5.2, EssentialsX-2.17.1.0, EssentialsXChat-2.17.1.0, EssentialsXSpawn-2.17.1.0, GUIShop, Lockette, LuckPerms-Bukkit-5.0.72, Multiverse-Core-2.5.0, Multiverse-Portals-2.5.0, MuteChat, PlaceholderAPI-2.10.4, PlugMan, Quests-3.8.5, RankGrantPlus, Scoreboard-revision, Shopkeepers-2.2.2, SortingHat, TheHousePoints-2.0.1-SNAPSHOT, ToggleBlock, Vault, ViaVersion-2.2.2, worldedit-bukkit-6.1.9 and worldguard-bukkit-6.2.2.

**Describe the bug**
When I cast "Expelliarmus" in the console it just comes up with this.
[10:10:20] [Server thread/WARN]: [HPS] Task #463 for HarryPotterSpells v1.1.9 BETA generated an exception
java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.Material.matchMaterial(Material.java:740) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at com.hpspells.core.spell.Expelliarmus$1.hitEntity(Expelliarmus.java:46) ~[?:?]
	at com.hpspells.core.SpellTargeter$3.run(SpellTargeter.java:193) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by jacklin213** [comment]
Thanks for providing the information requested from the template.
From initial investigations, it looks like the Spell was not able to find a material matching the wand type specified in the config under "wand.type".

Can you please send a http://pastebin.com of your config, or paste it directly in here using the insert code option.

Regards
Jack

**Comment by TheRealVIG0R** [comment]
https://pastebin.com/E7bTGUS8

**Comment by TheRealVIG0R** [comment]
@jacklin213 ?

**Comment by jacklin213** [comment]
Hey,

Thanks for providing the paste. This bug was fixed HPS v1.2.1 
https://dev.bukkit.org/projects/harrypotterspells/files/2831797

Please update to use this version and let me know if there are any further issues

**Comment by TheRealVIG0R** [comment]
Ok, thank you. Just saying that version doesn't seem to be compatible with 1.12.2, which is the version of my server.

**Comment by jacklin213** [comment]
Hey @TheRealVIG0R 

We do our best to maintain backward compatibility but due to the Spigot API requirements in 1.13.2 and 1.14.4, to use any of the new content we have to tag the plugin for that version. This means that we no longer can maintain backward compatibility pre 1.13.2. All the new features and versions of HPS going onward will at least require 1.13.2.

For the time being as the Expillarmus fix can be done in Spigot 1.12.2 I have created an unsupported build of HPS v1.1.9 which has this bug fixed. I've only briefly tested this, please let me know if you have any issues with the Spell

Download it [here](https://github.com/HarryPotterSpells/harrypotterspells.github.com/raw/master/releases/HarryPotterSpells-v1.1.9_U.jar)

**Comment by jacklin213** [comment]
Resolving issue as this bug has already been addressed in future versions and an unsupported build was provided with fix applied to HPS v1.1.9
